### ISSUE TITLE
Create basic home page

### ISSUE THREAD

**Issue by lenora4321** [CSI-280/MusicGames#11]
To be done only once we've got all the setup done, so that we can build this off of react and stuff.  We just need a starting point for the user interface, a splash screen.  Take a look at the design layout from issue #2  marked home page and go off of that.  Should include:

- nav bar
- links to other pages such as points and games (even if the don't go anywhere yet)
- link to home page in form of title
- blank space for our icon and maybe a little description

don't need to implement how the widget/playlist bar will work, so leave that out for now.

**Comment by jbuzzell** [comment]
dependencies #13 #20
