### ISSUE TITLE
Create Basic Games

### ISSUE THREAD

**Issue by NathanDiMauro** [CSI-280/MusicGames#12]
This is an issue that could easily be broken up into different groups. We need to code some basic mini games like Tic tac toe, Connect 4,  Fill in the lyrics, Guess the artist, Popularity gamibling/guessing, Guess the soundtrack, etc.

**Comment by lenora4321** [comment]
I can tentatively start off with tic tac toe and guess the lyric

**Comment by thomasszp** [comment]
I guess we need to define the criterea for what games we will have on our site, i.e if we're strictly music-related or not.

**Comment by A-Waters** [comment]
I was under the impressions of being games related to music, does anyone have the initial planning document we made on google? If so does that list any music specific games?

**Comment by lenora4321** [comment]
The list of games included on the planning sheet was:
Tic tac toe
Connect 4
Fill in the lyrics (type racing)
Guess the artist
Popularity gambling/guessing
Guess the soundtrack

**Comment by lenora4321** [comment]
Good news, you can now play basic tic-tac-toe against the computer.

**Comment by lenora4321** [comment]
Also, I can't get to programming anything like "guess the lyric" or most of the other music relate games until the API for Spotify is integrated with our website.

**Comment by lenora4321** [comment]
I changed this issue to an overarching issue, since each game would make a better standalone issue under this one, and will be submitting the infamous tic-tac-toe to that issue instead.
