### ISSUE TITLE
Come up with a name for our site

### ISSUE THREAD

**Issue by JakeCapra** [CSI-280/MusicGames#14]
This should definitely be something we all decide on. We could all submit one name, and then use a poll to choose it.

**Comment by A-Waters** [comment]
How about "Wacky and Wild Music Games" or "WWMG" for short?
(this was a joke)
I'm not sure about a real name

**Comment by JakeCapra** [comment]
"Playin" or "Just Playin"

**Comment by jbuzzell** [comment]
![tune](https://user-images.githubusercontent.com/29132172/77938503-d0f1a100-7283-11ea-9931-126c51eac47e.jpg)

**Comment by jbuzzell** [comment]
Extended Play

like an EP. we could do Long Play too

**Comment by NathanDiMauro** [comment]
I like Tune Town Online

**Comment by A-Waters** [comment]
I like Extended Play a lot. While I like Tune Town Online its also very memey (and if this ever becomes an actual thing, it could cause issues, I know that's like not the goal of this project BUT still)

**Comment by jbuzzell** [comment]
yeah, tunetown was definitely not a serious suggestion

**Comment by NathanDiMauro** [comment]
We all liked Extended Play EP for short.
