### ISSUE TITLE
Create a logo 

### ISSUE THREAD

**Issue by jbuzzell** [CSI-280/MusicGames#19]
interactive with/dependent on #14

**Comment by JakeCapra** [comment]
We need a name first, so I think we'll have to have #14 resolved before this can be started.

**Comment by thomasszp** [comment]
Do we have a working name for our website?

**Comment by JakeCapra** [comment]
@thomasszp see #14. As of now, we don't. But hopefully we will end up voting on one soon.

**Comment by jbuzzell** [comment]
i could come up with some designs and we can just backfill the title later

**Comment by thomasszp** [comment]
"Extended Play" seems to be what we're working with for now.

I'll try to have a few designs up soon, if anyone has a flash of inspiration for their own image post it here and we'll pick something.

![image](https://user-images.githubusercontent.com/28933646/78212799-c94a1c00-747e-11ea-85d9-20a358ad6b93.png)

**Comment by JakeCapra** [comment]
Can we close this?
