### ISSUE TITLE
Design Website layout

### ISSUE THREAD

**Issue by A-Waters** [CSI-280/MusicGames#2]
Weed a firm design for the website, how the UI is going to look ect. We should do this regardless of how we are going to executer the look in code and worry about that later. This should be focusing on how does the interface look to a user. if anyone has experience with like photoshop that would be great but you could also be like me and use MS paint and that would be fine. We should think about just nailing the home page for now.  we can tweak and edit the design later as we need to.

**Comment by chrisbendel** [comment]
Wireframing is a good approach to use when setting up initial designs. There are some free tools online, this one is really minimalistic if you need something basic

https://wireframe.cc/

Whoever works on this can keep it pretty simple, you dont need to worry about every little detail/where every button is exactly going to be on the page down to the pixel. Just get a general idea of where a nav bar might be, how a user might select between games, etc

**Comment by lenora4321** [comment]
https://wireframe.cc/M1mrci - potential home page
https://wireframe.cc/jFfvGD - potential game page
https://wireframe.cc/Xr0QFU - potential points page
https://wireframe.cc/K3sWXR - potential playlist page

**Comment by lenora4321** [comment]
The only other pages I can think of off the top of my head that I didn't give a potential layout for are maybe a login page, a user page (for changing user image and stuff), and a spend page for extras that aren't songs.  We have to decide if we want any of these and in what capacity, or we can group them with other pages.

**Comment by lenora4321** [comment]
Overall, I think we should have a simple layout that has the home page as the start location and then there can be options to go to spending points (playlist/maybe extras) and gaining points (games).  There should probably be some sort of mini "this song is playing" thing that can be found on any page, represented by the "widget" on the diagrams I made.  This could also be a bar on the side that shows the next songs up, or whatever we decide.  If there's anything else I should add, please speak now.  Obviously this can change as we go, but for a general guide of where we should go I think this fits the bill.
