### ISSUE TITLE
Create placeholder game pages

### ISSUE THREAD

**Issue by thomasszp** [CSI-280/MusicGames#21]
This issue should just create the basic pages to exist for when we decide on and begin to code said games.

Styling and layout are open-ended as of this point. These pages will only ever be linked to off the game/home page, but that functionality may be put off for another issue.

**Comment by A-Waters** [comment]
How does this differ from issue #2 ?

**Comment by chrisbendel** [comment]
@TAwc from what i gather this issue is actually, create the files/shell of what each game component might be, and possibly link them together using something like react rouer?

**Comment by thomasszp** [comment]
This issue just relates to creating the physical pages, that would later be worked on by adding games to them. Just having the pages exist in our site is an important step that needs to happen early on so nothing gets muddled up when everyone tries to make their own.

**Comment by A-Waters** [comment]
I see, Okay. Good idea!

**Comment by NathanDiMauro** [comment]
pull request #30
