### ISSUE TITLE
Create a Spotify Account

### ISSUE THREAD

**Issue by NathanDiMauro** [CSI-280/MusicGames#3]
Make a spotify account for us to use in the project. Make a decent username and password that everyone knows and has access too. This will help us use the spotify API in the website.

**Comment by chrisbendel** [comment]
This issue may expand in scope to doing all of the things in this quick start guide for developers here (I think you need to register your application with them to get the API key/secret)
https://developer.spotify.com/documentation/web-api/quick-start/

You guys also might want to flesh out some of the JS SDK's that already exist (to take some work off of implementing every single API call yourselves) - this could be another ticket to get it wired into your application https://developer.spotify.com/documentation/web-api/libraries/ - under Web API Wrappers -> javascript
I looked through them and personally I would use this one https://github.com/jmperez/spotify-web-api-js but feel free to pick one that makes the most sense for you guys

**Comment by A-Waters** [comment]
I have some experience with Spotify API already, however, I did work in python, not sure exactly how that will help if it going to.

**Comment by NathanDiMauro** [comment]
Thanks @chrisbendel that really fleshes out this issue. @TAwc if we use django then you could write in python still.

**Comment by NathanDiMauro** [comment]
Spotify account is all set up. The secrete and ID associated to our account can be found at this [link.](https://developer.spotify.com/dashboard/applications/42b56bb8489a418db8bd7d2c631b2eef) I sent everyone an email with our spotify account information.
