### ISSUE TITLE
Style the Games page

### ISSUE THREAD

**Issue by JakeCapra** [CSI-280/MusicGames#35]
The game page looks shit. I just threw it together, so it needs to be styled.
![image](https://user-images.githubusercontent.com/49655704/77977383-8f85e380-72cd-11ea-8444-11f2e52d3627.png)

**Comment by lenora4321** [comment]
Aight I'm on it

**Comment by NathanDiMauro** [comment]
@lenora4321 I already restyled the actual game itself issue #34 so I would sugest looking at those changed before styling the page.
