### ISSUE TITLE
First draft of a 'music widget'

### ISSUE THREAD

**Issue by NaomiHoniker** [CSI-280/MusicGames#37]
I suggest that we attempt to get the basics down of a 'widget', as we had suggested, to be on the screen, persisting with the same information, even as the user changes between different pages. I'm personally not quite sure how this would be done, but I'm very open to suggestions and working with people to do it. 

For reference, I'm envisioning the Spotify desktop app's little bottom left corner space, which displays the live timestamp of the song you're listening to, even as the user navigates the menus and pages. This may be out of scope for our project, so we could also use this issue as a discussion area for how we will make something else like this happen, while getting the same effect.

**Comment by JakeCapra** [comment]
See #36 and #13. The player is discussed in both of those. Also #36 is the same issue. Continuous playing is easy with React, look at #13 and some of the comments on there for more info.

**Comment by NaomiHoniker** [comment]
Oh, wow. Okay, yeah haha. I'll try and come up with a better issue in the next few days, then. We can close this one up, I guess?
