### ISSUE TITLE
Implement Google Sign-in

### ISSUE THREAD

**Issue by JakeCapra** [CSI-280/MusicGames#38]
> Google Sign-In is a secure authentication system that reduces the burden of login for your users, by enabling them to sign in with their Google Account—the same account they already use with Gmail, Play, and other Google services.

I think this is the easiest way to handle accounts on our site. Check it out [here](https://developers.google.com/identity).
Check out the code you would need to use [here](https://developers.google.com/identity/sign-in/web).
It is in html, but I also found [this](https://www.npmjs.com/package/react-google-login), which is built for react.

**Comment by A-Waters** [comment]
Uh, I'm no expert (really I'm not), but from my understanding, I was under the belief we were using Spotify for this. Someone correct me if I am wrong please.

**Comment by JakeCapra** [comment]
I think its best if we don't limit our players to people who have a Spotify account.
