### ISSUE TITLE
Review/Suggest for data models

### ISSUE THREAD

**Issue by NaomiHoniker** [CSI-280/MusicGames#46]
I created a basic data model for user data with Django/Rest framework, as per [Jake's issue](https://github.com/CSI-280/MusicGames/issues/31#issue-590627652). It'll look something like this:

User
-ID (So users can be uniquely identified, stored as string. Our primary key, if anyone remembers that from Database Management. Max length abt 20~~) 
-Public Access Key (String, max length 35)
-Username (Probably won't need to be much longer than 20 characters?)
-Points (Integer)

Any suggestions for things to add? [This site](https://docs.djangoproject.com/en/3.0/topics/db/models/) was very helpful as a refresher on database models. 

It's in backend\src\djreact\models.py if anyone wants to add any additional models or change anything to this model. Otherwise, suggest them here and I'll work on em myself!

**Comment by A-Waters** [comment]
Oh, snap, I didn't see your branch before writing my code. That's my bad, I didn't realize you were implementing, when I read this ticket I thought you were just shooting ideas, I'm so sorry. I implemented this basically in the commit listed above (with a few changes to get it working in full-fledged condition, but after looking at your code I might change a thing or two in mine) I looked at your code tho and I thought it was really well done... :/

**Comment by NaomiHoniker** [comment]
Oh, you're totally fine! I was just learning how to make it all work, tbh haha
I appreciate the help with it! Having two people looking at this kinda stuff is probably a good idea, since I'm still learning.
