### ISSUE TITLE
Initialize code base with Django/React

### ISSUE THREAD

**Issue by JakeCapra** [CSI-280/MusicGames#6]
Commit the starter code for Django/React, this includes files like app.js, index.html (for react). This can be done with npx create-react-app musicGames in the terminal. For Django, this can be done with django-admin startproject musicGames. I'm not sure if we've officially decided on a framework,m since the google doc lists both Django and React.

**Comment by chrisbendel** [comment]
@JakeCapra step 1 should be deciding on a framework, before having a task that says to implement a framework

**Comment by JakeCapra** [comment]
Commit the starter code for [Django](https://docs.djangoproject.com/en/3.0/intro/tutorial01/)/[React](https://reactjs.org/docs/create-a-new-react-app.html), this includes files like app.js, index.html (for react). This can be done with `npx create-react-app musicGames` in the terminal. For Django, this can be done with `django-admin startproject musicGames`. I'm not sure if we've officially decided on a framework,m since the google doc lists both Django and React.

**Comment by jbuzzell** [comment]
https://docs.djangoproject.com/en/3.0/intro/install/ django guide

**Comment by A-Waters** [comment]
@jbuzzell can you look at the 'alex' branch sometime soon, just double check I'm doing stuff right/you understand what's happening because I'm a little lost but it technically works. Its currently set up for articles tho.


I have moved on to the front side integration and I'm seeing where this leads me currently.

**Comment by A-Waters** [comment]
The front side has been set up and we are now able to communicate with it, I'm still confused about where we would be creating out 'users' but I think that will be next week's issue. Depending on what you think (@jbuzzell), we can better clarify what the next steps will be.

**Comment by jbuzzell** [comment]
how are you setting things up? when i run the django app i get an error. traceback:

![image](https://user-images.githubusercontent.com/29132172/77489199-d2e3dc00-6e0d-11ea-89c7-0c82c1292835.png)

**Comment by chrisbendel** [comment]
@TAwc are there env variables you set up locally?

**Comment by jbuzzell** [comment]
also, using the runserver command from manage.py (which theoretically should be the same thing) gives a different traceback:

![image](https://user-images.githubusercontent.com/29132172/77489710-54883980-6e0f-11ea-9226-12d959f012d4.png)

**Comment by A-Waters** [comment]
Give me a minute to try to reproduce the issue on my side. Im gonna see whats up.

**Comment by jbuzzell** [comment]
@TAwc oops my bad i didn't install like any dependencies at all

**Comment by A-Waters** [comment]
@jbuzzell I'm not able to recreate the issues on my machine, after cloning the files to a new directory, make sure you did the pip install correctly as the read me states below. I'm guessing based on the error you're getting you may have missed on.

As far as I know, my env variables haven't been touched.
 
Note I'm using python 3.6 just in case that is the issue

**Comment by A-Waters** [comment]
Yeah lmk if that works

**Comment by jbuzzell** [comment]
@TAwc close but no cigar. got django running, here's the npm traceback:

![image](https://user-images.githubusercontent.com/29132172/77490966-d3cb3c80-6e12-11ea-992d-e99377c01d02.png)
 
everything is installed properly now

**Comment by A-Waters** [comment]
cd into gui mb didnt put that in read me

**Comment by jbuzzell** [comment]
both servers run but it's looking like they're trying to compete for port 8000 and booting each other out


![image](https://user-images.githubusercontent.com/29132172/77491785-1aba3180-6e15-11ea-94f7-a03a952d4ac2.png)
![image](https://user-images.githubusercontent.com/29132172/77492003-be0b4680-6e15-11ea-8eab-64de46bce9e6.png)
![image](https://user-images.githubusercontent.com/29132172/77491811-3291b580-6e15-11ea-9245-571a17637caf.png)

i appreciate your patience through this btw

**Comment by jbuzzell** [comment]
unrelated to all of this, it looks like django was set up just fine. i would probably suggest moving the react project info into the django app directory in the future depending how react interacts with django's [template system](https://docs.djangoproject.com/en/3.0/intro/tutorial03/). i'll admit i'm not super familiar with react though, and i have never set it up in a django project, so i'm sure you're on the right track in that regard

**Comment by A-Waters** [comment]
What I think is happening here is that the Django API endpoint is returning a null object (because you haven't created an article, basically an empty object causing some issues, this is a big guess tho).  I'm not sure what you mean exactly with "moving the react project info into the django app directory in the future depending on how react interacts with django's template system." 

The big thing I think we want to make sure is that you can understand what's happening in the backend/src/ section. BUt ty so much for the help

**Comment by JakeCapra** [comment]
If someone were to have just cloned the repo, what would they have to do to get up and running? What dependencies would they have to install?

**Comment by A-Waters** [comment]
@JakeCapra check out the pull request #15, I think it should clarfy things
