### ISSUE TITLE
Clean up styles one last time before presentation

### ISSUE THREAD

**Issue by jbuzzell** [CSI-280/MusicGames#69]

**Comment by jbuzzell** [comment]
@CSI-280/web-people is there anything that needs cleaning up in particular stylewise? looking like #29 and #76 should be a big chunk of what we need.

**Comment by jbuzzell** [comment]
i am also willing to do general CSS stuff that you don't want to

**Comment by A-Waters** [comment]
I don't see anything major, but if you can find something go off.
