### ISSUE TITLE
Vote on framework to use

### ISSUE THREAD

**Issue by chrisbendel** [CSI-280/MusicGames#7]
I don't think you're going to need a 'backend' component of your website unless you want to actually use a database and store information? if so, you can use react/django together, react for UI components and django for interfacing with the database

@CSI-280/web-people

[![](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/React)](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/React/vote)
[![](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/Django)](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/Django/vote)
[![](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/React%20%26%20Django)](https://api.gh-polls.com/poll/01E2K42F5XJHQ4Y7TNEP4Y933C/React%20%26%20Django/vote)

**Comment by jbuzzell** [comment]
i have a lot of experience in django so i'd be willing to spearhead that effort

**Comment by chrisbendel** [comment]
If anyone is unfamiliar with django https://stackoverflow.com/a/9081179/12115005

**Comment by A-Waters** [comment]
I have some limited experience with react using hooks (the previous project) and don't know a lot of js but I do have *some* experience. I'm happy to work in it just incase that wasnt clear.

**Comment by chrisbendel** [comment]
@TAwc in regards to react and hooks vs no hooks, the great thing about react is that you can use both hooks and regular class components in a project

**Comment by chrisbendel** [comment]
React & Django 🏆
