### ISSUE TITLE
Create visual design language & style guide

### ISSUE THREAD

**Issue by jbuzzell** [CSI-280/MusicGames#8]
this includes

- color palettes

- fonts

- buttons/component styles (i.e. when we create a new component in react, what should it look like?)

- page layout/flow (i.e. what should draw the user's attention first? what do all pages need to have in common with each other?)

this will be highly interactive with #2. style guide will be a PDF/image infographic with all of the above--ideally at least two designs will go through a review process.

**Comment by jbuzzell** [comment]
i would like to have a heavy role in this as UI/UX programming for the web is my area of expertise.

**Comment by jbuzzell** [comment]
@CSI-280/web-people what do we think of this? such a document would make work like #2 a lot easier & simplify/reduce time spent on styling in the future.

**Comment by A-Waters** [comment]
While I think this is a good idea, I'm worried about catching all the, what I guess we could call "edge cases", and completing it in a reasonable amount of time. I think it could definitely be beneficial.

**Comment by JakeCapra** [comment]
If you're looking for color themes, you should definitely check out[ this site](https://color.adobe.com/explore?page=2), its got a bunch of color themes to choose from, and you can creat your own.

**Comment by A-Waters** [comment]
I was using pylinter and pep8 to stylize the python code in the backside when I created it. So if we want to we can just use that. for the backside.

**Comment by jbuzzell** [comment]
@TAwc wrong type of styleguide. you're thinking code whereas the result of this task will be sample color schemes, component designs, fonts in a pdf for use when developing css

**Comment by A-Waters** [comment]
O I C

**Comment by jbuzzell** [comment]
![CSI280 STYLE BIBLE LIGHT@2x](https://user-images.githubusercontent.com/29132172/77598800-28d18600-6ed9-11ea-8099-fa48ed5e4866.png)

![CSI280 STYLE BIBLE DARK@2x](https://user-images.githubusercontent.com/29132172/77598805-2cfda380-6ed9-11ea-8d5d-ae828113d421.png)

![CSI280 STYLE BIBLE PLAYER@2x](https://user-images.githubusercontent.com/29132172/77598809-2f5ffd80-6ed9-11ea-818f-3ea00278149f.png)

**Comment by jbuzzell** [comment]
god i forgot to put the padding for everything that isn't buttons hold up

**Comment by jbuzzell** [comment]
![CSI280 STYLE BIBLE LIGHT@2x](https://user-images.githubusercontent.com/29132172/77599227-77cbeb00-6eda-11ea-90cc-b20ac14f1b5f.png)

![CSI280 STYLE BIBLE DARK@2x](https://user-images.githubusercontent.com/29132172/77599234-7b5f7200-6eda-11ea-8852-6527a37ce2b1.png)

![CSI280 STYLE BIBLE PLAYER@2x](https://user-images.githubusercontent.com/29132172/77599148-33404f80-6eda-11ea-99e4-ba6ced2138e7.png)

@CSI-280/web-people what do we think of these? i figure the gamers in the room will prefer the dark theme but lmk

**Comment by jbuzzell** [comment]
fyi the player is supposed to be the player shown in the wireframes displayed in #2 (i made it before the styleguides so it doesn't necessarily follow the laws to a tee)

**Comment by jbuzzell** [comment]
aileron is an adobe font that we should all be able to access for this project (and so cute!)

**Comment by A-Waters** [comment]
I like it. I dont how exactly its going to be exacuted in code yet, but thats for a different time.

**Comment by NaomiHoniker** [comment]
I think that looks great!

**Comment by JakeCapra** [comment]
@jbuzzell When you say "Headers" do you mean the navbar?

**Comment by jbuzzell** [comment]
@jbuzzell yeah, generally, but that can be a bit flexible

**Comment by JakeCapra** [comment]
@jbuzzell I think we need to rethink the font size. It takes up way to much space on the navbar. (using the headers and subheaders font size)
![Annotation 2020-03-27 141830](https://user-images.githubusercontent.com/49655704/77787545-16209380-7036-11ea-8c79-6c9161f4866e.png)

**Comment by jbuzzell** [comment]
hm, yeah. try 64px. worst case we can scale them all down to:

header: 48
subheader: 32
body: 18

this was mostly just me messing with things in XD, so i'm not married to font sizes.

**Comment by JakeCapra** [comment]
I ended up using 2vw and 1.5vw, which came out pretty nice imo. I think its best to use viewport since it changes based on screen size.
![image](https://user-images.githubusercontent.com/49655704/77949316-bd026b00-7294-11ea-98a1-5e58e51a4a82.png)

**Comment by NathanDiMauro** [comment]
Is this done now can the issue be closed?

**Comment by jbuzzell** [comment]
i'd say it can be closed but it should probably remain pinned
